[package]
name = "brotli-wasm-rust"
version = "0.0.0"
authors = ["Nirmal Manandhar"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.11"
brotli = "2.5.0"

[profile.release]
lto = true
